export const mockSheets = {
  site_settings: [
    {
      site_name: 'Blue Date Coffee Shop',
      site_language: 'uk',
      logo_url: '',
      footer_eyebrow: 'Blue Date Coffee Shop',
      footer_title: 'Дніпро. Чистий смак. Спокійний ритм.',
      footer_address_label: 'Адреса',
      footer_hours_label: 'Години роботи',
      footer_links_label: 'Посилання',
      address: 'вул. Січеславська Набережна, Дніпро, Україна',
      work_hours: 'Щодня 08:00 - 21:00',
      instagram_url: 'https://instagram.com',
      telegram_url: 'https://t.me',
      google_reviews_url: 'https://www.google.com/maps',
    },
  ],
  categories: [
    {
      slug: 'kava',
      name_uk: 'Кава',
      description_uk: 'Еспресо, молочні напої та чистий смак щодня.',
      order: 1,
      is_active: true,
    },
    {
      slug: 'matcha',
      name_uk: 'Матча',
      description_uk: 'Матча у спокійному, чистому та збалансованому стилі.',
      order: 2,
      is_active: true,
    },
    {
      slug: 'cold-coffee',
      name_uk: 'Холодна кава',
      description_uk: 'Холодні кавові позиції для легкого ритму дня.',
      order: 3,
      is_active: true,
    },
    {
      slug: 'cold-matcha',
      name_uk: 'Холодна матча',
      description_uk: 'Свіжа подача матчі з чистою текстурою.',
      order: 4,
      is_active: true,
    },
    {
      slug: 'ice-tea',
      name_uk: 'Айс-ті',
      description_uk: 'Легкі чайні напої з холодною подачею.',
      order: 5,
      is_active: true,
    },
    {
      slug: 'cacao',
      name_uk: 'Какао',
      description_uk: 'Насичені какао-позиції для мʼякого смаку.',
      order: 6,
      is_active: true,
    },
    {
      slug: 'tea',
      name_uk: 'Заварні чаї',
      description_uk: 'Класичні заварні чаї на щодень.',
      order: 7,
      is_active: true,
    },
    {
      slug: 'desserts',
      name_uk: 'Десерти',
      description_uk: 'Лаконічні десерти, що добре поєднуються з кавою.',
      order: 8,
      is_active: true,
    },
    {
      slug: 'sandwiches',
      name_uk: 'Сендвічі',
      description_uk: 'Швидкі солоні позиції для сніданку та обіду.',
      order: 9,
      is_active: true,
    },
  ],
  menu_items: [
    {
      id: '1',
      category_slug: 'kava',
      name_uk: 'Еспресо Blue Line',
      serving_uk: '40 мл',
      description_uk: 'Щільний еспресо з чистою кислотністю та сухим післясмаком.',
      price: 80,
      image_url: '/placeholders/blue-date-1.svg',
      badge: 'new',
      is_active: true,
      order: 1,
    },
    {
      id: '2',
      category_slug: 'kava',
      name_uk: 'Flat White',
      serving_uk: '180 мл',
      description_uk: 'Молочна текстура, збалансований профіль та короткий фініш.',
      price: 120,
      image_url: '/placeholders/blue-date-2.svg',
      badge: '',
      is_active: true,
      order: 2,
    },
    {
      id: '3',
      category_slug: 'matcha',
      name_uk: 'Церемоніальна матча',
      serving_uk: '250 мл',
      description_uk: 'Яскравий зелений профіль, чистий смак і мінеральна свіжість.',
      price: 160,
      image_url: '/placeholders/blue-date-3.svg',
      badge: 'vegan',
      is_active: true,
      order: 1,
    },
    {
      id: '4',
      category_slug: 'cold-coffee',
      name_uk: 'Cold Brew',
      serving_uk: '250 мл',
      description_uk: 'Довга екстракція, холодна подача та сухий какаовий тон.',
      price: 140,
      image_url: '/placeholders/blue-date-1.svg',
      badge: 'cold',
      is_active: true,
      order: 1,
    },
    {
      id: '5',
      category_slug: 'cold-matcha',
      name_uk: 'Blue Matcha Tonic',
      serving_uk: '300 мл',
      description_uk: 'Матча, тонік і лимонна нота з крижано чистою подачею.',
      price: 170,
      image_url: '/placeholders/blue-date-2.svg',
      badge: 'cold',
      is_active: true,
      order: 1,
    },
    {
      id: '6',
      category_slug: 'ice-tea',
      name_uk: 'Jasmine Ice Tea',
      serving_uk: '300 мл',
      description_uk: 'Легка квіткова ароматика та мінімальна солодкість.',
      price: 110,
      image_url: '/placeholders/blue-date-3.svg',
      badge: '',
      is_active: true,
      order: 1,
    },
    {
      id: '7',
      category_slug: 'cacao',
      name_uk: 'Cold Cacao',
      serving_uk: '250 мл',
      description_uk: 'Насичене какао на льоду з мʼякою текстурою.',
      price: 150,
      image_url: '/placeholders/blue-date-1.svg',
      badge: 'cold',
      is_active: true,
      order: 1,
    },
    {
      id: '8',
      category_slug: 'tea',
      name_uk: 'Sencha Clean',
      serving_uk: '400 мл',
      description_uk: 'Зелений чай з прозорим ароматом і довгим фінішем.',
      price: 140,
      image_url: '/placeholders/blue-date-2.svg',
      badge: '',
      is_active: true,
      order: 1,
    },
    {
      id: '9',
      category_slug: 'desserts',
      name_uk: 'Lemon Cloud',
      serving_uk: '1 шт',
      description_uk: 'Десерт із легкою кислинкою та чистою геометрією подачі.',
      price: 165,
      image_url: '/placeholders/blue-date-3.svg',
      badge: 'sold out',
      is_active: true,
      order: 1,
    },
    {
      id: '10',
      category_slug: 'sandwiches',
      name_uk: 'Turkey Blue Sandwich',
      serving_uk: '1 шт',
      description_uk: 'Індичка, крем-сир та свіжість зелені в стриманій збірці.',
      price: 210,
      image_url: '/placeholders/blue-date-1.svg',
      badge: 'new',
      is_active: true,
      order: 1,
    },
  ],
  seo: [
    {
      meta_title: 'Blue Date Coffee Shop | Premium menu board in Dnipro',
      meta_description:
        'Blue Date Coffee Shop у Дніпрі: editorial minimal лендинг із меню, сезонними позиціями та переходами на Instagram, Telegram і Google Reviews.',
      og_title: 'Blue Date Coffee Shop',
      og_description:
        'Преміальний мінімалістичний лендинг кавʼярні в Дніпрі з меню та Google Sheets як CMS.',
      og_image_url: '/placeholders/blue-date-1.svg',
      canonical_url: 'https://bluedate.example.com',
    },
  ],
}
